services:
  tdarr:
      container_name: tdarr
      image: ghcr.io/haveagitgat/tdarr:latest
      networks:
      - m3tv
      restart: unless-stopped
      #network_mode: bridge
      ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - UMASK_SET=002
      - serverIP=$serverIP
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - nodeName=MainNode
      #For Intel QSV
      - ffmpegVersion=6
      
      # For NVIDIA_GraphicsCards
      #- NVIDIA_DRIVER_CAPABILITIES=all
      #- NVIDIA_VISIBLE_DEVICES=all
      
      volumes:
      - $path/tdarr/server:/app/server
      - $path/tdarr/configs:/app/configs
      - $path/tdarr/logs:/app/logs
      - $path/tdarr/transcode_cache:/temp
      - media:/media:nocopy
      - public:/public:nocopy
      
      # For NVIDIA_GraphicsCards
      #runtime: nvidia
      
      #For Intel QSV
      devices:
      - /dev/dri:/dev/dri

networks:
  m3tv:
    external: true
      
#For nfs share  
volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":PATH"
  public:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":PATH"