services:
    prowlarr:
      container_name: prowlarr
      image: lscr.io/linuxserver/prowlarr:latest
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      ports:
      - 9696:9696
      volumes:
      - $path/prowlarr:/app/config
      restart: unless-stopped

#For nfs share 
volumes:
  media:
    external: true