services:
    prowlarr:
      image: lscr.io/linuxserver/prowlarr:latest
      networks:
      - m3tv
      container_name: prowlarr
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      ports:
      - 9696:9696
      volumes:
      - $path/prowlarr:/config
      restart: unless-stopped

networks:
  m3tv:
    external: true