---
version: "2"
services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=jellyfin.example.com
    volumes:
      - /homelab/conf/jellyfin:/config
      - /homelab/media:/media
      - /homelab/media/Airing:/Airing
      - /homelab/media/Finished Airing:/FinishedAiring
      - /homelab/media/TV Shows:/TV Shows
      - /homelab/media/movies:/movies

    ports:
      - 8096:8096

    restart: unless-stopped
    
    jellyseerr:
      image: fallenbagel/jellyseerr:latest
      container_name: jellyseerr
      environment:
            - LOG_LEVEL=debug
            - TZ=Asia/Tashkent
      ports:
            - 5055:5055
      volumes:
      - /homelab/conf/jellyseerr:/app/config
      - /homelab/media:/media
      - /homelab/media/Airing:/Airing
      - /homelab/media/Finished Airing:/FinishedAiring
      - /homelab/media/TV Shows:/TV Shows
      - /homelab/media/movies:/movies
      restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /homelab/conf/jackett:/config
      - /homelab/media:/media
      - /homelab/media/Airing:/Airing
      - /homelab/media/Finished Airing:/FinishedAiring
      - /homelab/media/TV Shows:/TV Shows
      - /homelab/media/movies:/movies
      ports:
      - 9117:9117
    restart: unless-stopped
    
  organizr:
    image: linuxserver/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /homelab/conf/organizr:/config
    ports:
      - 9983:80
    restart: unless-stopped
  
    qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=10095
    volumes:
      - /homelab/conf/qbittorrent:/config
      - /homelab/media:/media
      - /homelab/media/Airing:/Airing
      - /homelab/media/Finished Airing:/FinishedAiring
      - /homelab/media/TV Shows:/TV Shows
      - /homelab/media/movies:/movies
    ports:
      - 10095:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /homelab/conf/transmission:/config
      - /homelab/media:/media
      - /homelab/media/Airing:/Airing
      - /homelab/media/Finished Airing:/FinishedAiring
      - /homelab/media/TV Shows:/TV Shows
      - /homelab/media/movies:/movies
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Denver
      - UMASK_SET=022 #optional
    volumes:
      - /homelab/conf/radarr:/config
      - /homelab/media:/media
      - /homelab/media/Airing:/Airing
      - /homelab/media/Finished Airing:/FinishedAiring
      - /homelab/media/TV Shows:/TV Shows
      - /homelab/media/movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /homelab/conf/bazarr:/config
      - /homelab/media:/media
      - /homelab/media/Airing:/Airing
      - /homelab/media/Finished Airing:/FinishedAiring
      - /homelab/media/TV Shows:/TV Shows
      - /homelab/media/movies:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
    
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Denver
    volumes:
      - /homelab/conf/sabnzbd:/config
      - /homelab/media:/media
      - /homelab/media/Airing:/Airing
      - /homelab/media/Finished Airing:/FinishedAiring
      - /homelab/media/TV Shows:/TV Shows
      - /homelab/media/movies:/movies
    ports:
      - 8181:8080
      - 9191:9090
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Denver
      - UMASK_SET=022
    volumes:
      - /homelab/conf/sonarr:/config
      - /homelab/media:/media
      - /homelab/media/Airing:/Airing
      - /homelab/media/Finished Airing:/FinishedAiring
      - /homelab/media/TV Shows:/TV Shows
      - /homelab/media/movies:/movies
    ports:
      - 8989:8989
    restart: unless-stopped

  requestrr:
    image: lscr.io/linuxserver/requestrr:latest
    container_name: requestrr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /homelab/conf/requestrr:/config
    ports:
      - 4545:4545
    restart: unless-stopped

## System Monitoring

  prometheus:
      image: prom/prometheus
      container_name: prometheus
      environment:
        - PUID=998
        - PGID=100
        - TZ=Etc/UTC
        - UMASK_SET=022
      volumes:
      - /homelab/conf/prometheus:/config
      ports:
        - 9292:9090
      restart: unless-stopped

  node-exporter:
      image: quay.io/prometheus/node-exporter:latest
      container_name: node-exporter
      network_mode: host
      environment:
        - PUID=998
        - PGID=100
        - TZ=Etc/UTC
        - UMASK_SET=022
      volumes:
        - /:/host:ro,rslave
      ports:
        - 9100:9090
      restart: unless-stopped
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - PUID=998
      - PGID=100
      - TZ=Etc/UTC
      - UMASK_SET=022
    ports:
      - 3000:3000
    restart: unless-stopped
       
  guacamole:
    image: flcontainers/guacamole
    container_name: guacamole
    environment:
      - TZ=Etc/UTC
      EXTENSIONS: 'auth-totp,auth-ldap'
    volumes:
      - postgres:/config
    ports:
      - 8080:8080
volumes:
  postgres:
    driver: local
    
    app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    
    ## Cloudflare-DDNS
    
      cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=xxxxxxx
      - ZONE=example.com
      - PROXIED=true
      - PUID=998
      - PGID=100
