---
version: "2"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    networks:
    -nginxproxymanager_default
    volumes:
    -/home/docker/vaultwarden:/data
    ports:
    80:80
    restart: unless-stopped

networks: 
  nginxproxymanager_default:
    external: true
  
