version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns
    restart: always
    environment:
      - API_KEY=$API_KEY
      - ZONE=$ZONE
      - PROXIED=true
      - PUID=$PUID
      - PGID=$PGID