version: "2"
services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    networks:
      - guacnetwork
    volumes:
      - $path/guacamole:/config
    ports:
      - 8182:8080
volumes:
  postgres:
    driver: local

networks:
  guacnetwork:
    driver: bridge

#Default Username == "guacadmin"
#Default Password == "guacadmin"