version: "3.1"
services:
  guacamole:
    image: flcontainers/guacamole
    container_name: guacamole
    environment:
      TZ: $TZ
    volumes:
      - $path/guacamole:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8182:8080

#Default Username == "guacadmin"
#Default Username == "guacadmin"