version: "2"
services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    volumes:
      - $path/guacamole:/config
    ports:
      - 8182:8080
volumes:
  postgres:
    driver: local