version: "2"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
    - $path/vaultwarden:/data
    ports:
    - 85:80
    restart: unless-stopped
