version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp
    environment:
      TZ: $TZ
      WEBPASSWORD: <webpassword>
    volumes:
      - $path/pihole/etc-pihole:/etc/pihole
      - $path/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped