services:
    radarr:
      image: linuxserver/radarr
      container_name: radarr
      environment:
      - PUID=$PUID
      - PGID=env
      - TZ=$TZ
      volumes:
      - $path/radarr:/config
      - media:/media
      ports:
      - 7878:7878
      restart: unless-stopped

    radarr-public:
      image: linuxserver/radarr:latest
      container_name: radarr-public
      environment:
      - PUID=$PUID
      - PGID=env
      - TZ=$TZ
      volumes:
      - $path/radarr-public:/config
      - public:/public
      ports:
      - 7070:7878
      restart: unless-stopped
      
#For nfs share  
volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":path/media"
  public:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":path/public"