services:
    radarr:
      image: linuxserver/radarr
      networks:
      - m3tv
      container_name: radarr
      environment:
      - PUID=$PUID
      - PGID=env
      - TZ=$TZ
      volumes:
      - $path/radarr:/config
      - media:/media:nocopy
      - downloads:/downloads:nocopy
      ports:
      - 7878:7878
      restart: unless-stopped

    radarr-public:
      image: linuxserver/radarr:latest
      networks:
      - m3tv
      container_name: radarr-public
      environment:
      - PUID=$PUID
      - PGID=env
      - TZ=$TZ
      volumes:
      - $path/radarr-public:/config
      - public:/public:nocopy
      - downloads:/downloads:nocopy
      ports:
      - 7070:7878
      restart: unless-stopped

networks:
  m3tv:
    external: true
      
#For nfs share  
volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":path"
  public:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":path"
  downloads:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":path"