version: "2"
services:
    radarr:
      image: linuxserver/radarr
      container_name: radarr
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      volumes:
      - $conf/radarr:/config
      - $media:/media
      ports:
      - 7878:7878
      restart: unless-stopped