version: "2"
services:
    jellyfin:
      image: lscr.io/linuxserver/jellyfin:latest
      container_name: jellyfin
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - JELLYFIN_PublishedServerUrl=jellyfin.example.com
      #For Nvidia GPU
      - NVIDIA_VISIBLE_DEVICES=all
      volumes:
      - $conf/jellyfin:/config
      - $media:/media
      ports:
      - 8096:8096
      #For Nvidia GPU
      runtime: nvidia
      restart: unless-stopped

    jellyseerr:
      image: fallenbagel/jellyseerr:latest
      container_name: jellyseerr
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - LOG_LEVEL=debug
      - TZ=$TZ
      volumes:
      - $conf/jellyseer:/app/config
      ports:
      - 5055:5055
      restart: unless-stopped

    sonarr:
      image: linuxserver/sonarr:develop
      container_name: sonarr
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022
      volumes:
      - $conf/sonarr:/config
      - $media:/media
      ports:
      - 8989:8989
      restart: unless-stopped

    radarr:
      image: linuxserver/radarr
      container_name: radarr
      environment:
      - PUID=$PUID
      - PGID=env
      - TZ=$TZ
      volumes:
      - $conf/radarr:/config
      - $media:/media
      ports:
      - 7878:7878
      restart: unless-stopped

    prowlarr:
      container_name: prowlarr
      image: lscr.io/linuxserver/prowlarr:latest
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      ports:
      - 9696:9696
      volumes:
      - $conf/prowlarr:/app/config
      restart: unless-stopped

    bazarr:
      image: lscr.io/linuxserver/bazarr:latest
      container_name: bazarr
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      volumes:
      - $conf/bazarr:/config
      - $media:/media
      ports:
      - 6767:6767
      restart: unless-stopped

    transmission:
      image: lscr.io/linuxserver/transmission:latest
      container_name: transmission
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      volumes:
      - $conf/transmission:/config
      - $media:/media
      ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      restart: unless-stopped

    tdarr:
      container_name: tdarr
      image: ghcr.io/haveagitgat/tdarr:latest
      restart: unless-stopped
      network_mode: bridge
      ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - UMASK_SET=002
      - serverIP=env/serverIP
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - nodeName=MainNode
      # For NVIDIA_GraphicsCards
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      volumes:
      - $conf/tdarr/server:/app/server
      - $conf/tdarr/configs:/app/configs
      - $conf/tdarr/logs:/app/logs
      - $media:/media
      - $conf/tdarr/transcode_cache:/temp
      # For NVIDIA_GraphicsCards
      runtime: nvidia
