services:
    sonarr:
      image: linuxserver/sonarr:develop
      container_name: sonarr
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022
      volumes:
      - $path/sonarr:/config
      - media:/media
      ports:
      - 8989:8989
      restart: unless-stopped

    sonarr-2:
      image: linuxserver/sonarr:develop
      container_name: sonarr-2
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022
      volumes:
      - $path/sonarr-2:/config
      - media:/media
      ports:
      - 8080:8989
      restart: unless-stopped

#For nfs share 
volumes:
  media:
    external: true