services:
    sonarr:
      image: linuxserver/sonarr:develop
      networks:
      - m3tv
      container_name: sonarr
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022
      volumes:
      - $path/sonarr:/config
      - media:/media:nocopy
      - downloads:/downloads:nocopy
      ports:
      - 8989:8989
      restart: unless-stopped

    sonarr-public:
      image: linuxserver/sonarr:develop
      networks:
      - m3tv
      container_name: sonarr-public
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022
      volumes:
      - $path/sonarr-public:/config
      - public:/public:nocopy
      - downloads:/downloads:nocopy
      ports:
      - 8080:8989
      restart: unless-stopped

networks:
  m3tv:
    external: true

#For nfs share  
volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":PATH"
  public:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":PATH"
  downloads:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":PATH"