services:
    sonarr:
      image: linuxserver/sonarr:develop
      networks:
      - media
      container_name: sonarr
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022
      volumes:
      - $path/sonarr:/config
      - media:/media
      ports:
      - 8989:8989
      restart: unless-stopped

    sonarr-public:
      image: linuxserver/sonarr:develop
      networks:
      - media
      container_name: sonarr-public
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022
      volumes:
      - $path/sonarr-public:/config
      - public:/public
      ports:
      - 8080:8989
      restart: unless-stopped

networks:
  media:

#For nfs share  
volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=ip,nolock,rw,soft,nfsvers=4"
      device: ":nfs-path/media"
  public:
    driver_opts:
      type: "nfs"
      o: "addr=ip,nolock,rw,soft,nfsvers=4"
      device: ":nfs-path/public"