version: "2"
services:
    sonarr:
      image: linuxserver/sonarr:develop
      container_name: sonarr
      environment:
      - PUID=env/PUID
      - PGID=env/PGID
      - TZ=env/TZ
      - UMASK_SET=022
      volumes:
      - env/path/conf/sonarr:/config
      - env/path/media:/media
      ports:
      - 8989:8989
      restart: unless-stopped