version: "2"
services:
    sonarr:
      image: linuxserver/sonarr:develop
      container_name: sonarr
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022
      volumes:
      - $conf/sonarr:/config
      - $media:/media
      ports:
      - 8989:8989
      restart: unless-stopped