version: '3.5'
services:
  prefetcharr:
    image: phueber/prefetcharr:latest
    networks:
      - m3tv
    container_name: prefetcharr
    environment:
      # `jellyfin`, `emby` or `plex`
      - MEDIA_SERVER_TYPE=jellyfin
      # Jellyfin/Emby/Plex baseurl
      - MEDIA_SERVER_URL=http://example.com/jellyfin
      # Jellyfin/Emby API key or plex server token
      - MEDIA_SERVER_API_KEY=<YOUR KEY HERE>
      # Sonarr baseurl
      - SONARR_URL=http://example.com/sonarr
      # Sonarr API key
      - SONARR_API_KEY=<YOUR KEY HERE>
      # Logging directory
      - LOG_DIR=/log
      # Log level
      - RUST_LOG=prefetcharr=debug
      # Polling interval in seconds
      - INTERVAL=900
      # The last <NUM> episodes trigger a search
      - REMAINING_EPISODES=2
    volumes:
      - /path/to/log/dir:/log
    restart: unless-stopped

networks:
  m3tv:
    external: true