version: "2"
services:
    jellyseerr:
      image: fallenbagel/jellyseerr:latest
      container_name: jellyseerr
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - LOG_LEVEL=debug
      - TZ=$TZ
      volumes:
      - $conf/jellyseer:/app/config
      ports:
      - 5055:5055
      restart: unless-stopped

