services:
    jellyseerr:
      image: fallenbagel/jellyseerr:latest
      networks:
      - media
      container_name: jellyseerr
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - LOG_LEVEL=debug
      - TZ=$TZ
      volumes:
      - $path/jellyseer:/app/config
      ports:
      - 5055:5055
      restart: unless-stopped

networks:
  media:
