version: '3.3'
services:
    homarr:
        container_name: homarr
        image: ghcr.io/ajnart/homarr:latest
        volumes:
            - 'env/path/homarr/configs:/app/data/configs'
            - 'env/path/homarr/icons:/app/public/icons'
        ports:
            - '7575:7575'
        restart: unless-stopped