version: '3.3'
services:
    homarr:
        container_name: homarr
        image: ghcr.io/ajnart/homarr:latest
        volumes:
            - '$path/homarr/configs:/app/data/configs'
            - '$path/homarr/icons:/app/public/icons'
            -  '/var/run/docker.sock:/var/run/docker.sock'
        ports:
            - '7575:7575'
        restart: unless-stopped