
version: "3.8"
services:
  cloudflared:
    image: cloudflare/cloudflared:latest #update the verion where necessary
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - proxy
    command: tunnel --config /home/nonroot/.cloudflared/config.yml run UUID #Replace UUID with your actual UUID
    volumes:
      - /opt/appdata/cloudflared/data:/home/nonroot/.cloudflared/
networks:
  proxy:
    driver: bridge
    external: true

  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=xxxxxxx
      - ZONE=example.com
      - SUBDOMAIN=subdomain
      - PROXIED=false

    client:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./src:/usr/share/nginx/html

    healthcheck:
        test: curl --fail http://localhost || exit 1
        interval: 60s
        retries: 5
        start_period: 20s
        timeout: 10s
