version: "2"
services:
    jellyfin:
      image: lscr.io/linuxserver/jellyfin:latest
      container_name: jellyfin
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - JELLYFIN_PublishedServerUrl=jellyfin.example.com
      #For Nvidia GPU
      - NVIDIA_VISIBLE_DEVICES=all
      volumes:
      - $conf/jellyfin:/config
      - $media:/media
      ports:
      - 8096:8096
      #For Nvidia GPU
      runtime: nvidia
      restart: unless-stopped