services:
    jellyfin:
      image: lscr.io/linuxserver/jellyfin:latest
      container_name: jellyfin
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - JELLYFIN_PublishedServerUrl=jellyfin.example.com
      #For Intel GPU
      #- linuxserver/mods:jellyfin-opencl-intel
      #For Nvidia GPU
      #- NVIDIA_VISIBLE_DEVICES=all
      volumes:
      - $path/jellyfin:/config
      - media:/media
      - public:/public
      ports:
      - 8096:8096

      #For Intel GPU
      #devices:
      #- /dev/dri:/dev/dri
      #For Nvidia GPU
      #runtime: nvidia

      restart: unless-stopped

#For nfs share  
volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":path/media"
  public:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":path/public"