version: "1.5"
services:
    prometheus:
      image: prom/prometheus
      container_name: prometheus
      environment:
        - PUID=998
        - PGID=100
        - TZ=Etc/UTC
        - UMASK_SET=022
      volumes:
      - /homelab/conf/prometheus:/config
      ports:
        - 9292:9090
      restart: unless-stopped

    node-exporter:
      image: quay.io/prometheus/node-exporter:latest
      container_name: node-exporter
      network_mode: host
      environment:
        - PUID=998
        - PGID=100
        - TZ=Etc/UTC
        - UMASK_SET=022
      volumes:
        - /:/host:ro,rslave
      ports:
        - 9100:9090
      restart: unless-stopped
    
    grafana:
      image: grafana/grafana
      container_name: grafana
      environment:
      - PUID=998
      - PGID=100
      - TZ=Etc/UTC
      - UMASK_SET=022
      ports:
      - 3000:3000
      restart: unless-stopped
    
    guacamole:
      image: flcontainers/guacamole
      container_name: guacamole
      environment:
      - TZ=Etc/UTC
      EXTENSIONS: 'auth-totp,auth-ldap'
      volumes:
      - postgres:/config
      ports:
      - 8080:8080
      postgres:
      driver: local