services:
    transmission:
      image: lscr.io/linuxserver/transmission:latest
      networks:
      - media
      container_name: transmission
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      volumes:
      - $path/transmission:/config
      - media:/media
      - public:/public
      ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      restart: unless-stopped

networks:
  media:

#For nfs share  
volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=ip,nolock,rw,soft,nfsvers=4"
      device: ":nfs-path/media"
  public:
    driver_opts:
      type: "nfs"
      o: "addr=ip,nolock,rw,soft,nfsvers=4"
      device: ":nfs-path/public"