services:
    transmission:
      image: lscr.io/linuxserver/transmission:latest
      container_name: transmission
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      volumes:
      - $path/transmission:/config
      - media:/media
      ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      restart: unless-stopped

#For nfs share 
volumes:
  media:
    external: true