version: "2"
services:
    transmission:
      image: lscr.io/linuxserver/transmission:latest
      container_name: transmission
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      volumes:
      - $conf/transmission:/config
      - $media:/media
      ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      restart: unless-stopped