services:
    bazarr:
      image: lscr.io/linuxserver/bazarr:latest
      networks:
      - media
      container_name: bazarr
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      volumes:
      - $path/bazarr:/config
      - media:/media
      ports:
      - 6767:6767
      restart: unless-stopped

    bazarr-public:
      image: linuxserver/bazarr:latest
      networks:
      - media
      container_name: bazarr-public
      environment:
      - PUID=$PUID
      - PGID=env
      - TZ=$TZ
      volumes:
      - $path/bazarr-public:/config
      - public:/public
      ports:
      - 6060:6767
      restart: unless-stopped

networks:
  media:
  
volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=ip,nolock,rw,soft,nfsvers=4"
      device: ":nfs-path/media"
  public:
    driver_opts:
      type: "nfs"
      o: "addr=ip,nolock,rw,soft,nfsvers=4"
      device: ":nfs-path/public"
