services:
    bazarr:
      image: linuxserver/bazarr:latest
      networks:
      - m3tv
      container_name: bazarr
      environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      volumes:
      - $path/bazarr:/config
      - media:/media:nocopy
      ports:
      - 6767:6767
      restart: unless-stopped

    bazarr-public:
      image: linuxserver/bazarr:latest
      networks:
      - m3tv
      container_name: bazarr-public
      environment:
      - PUID=$PUID
      - PGID=env
      - TZ=$TZ
      volumes:
      - $path/bazarr-public:/config
      - public:/public:nocopy
      ports:
      - 6060:6767
      restart: unless-stopped

#networks:
  #m3tv:
    #name: m3tv
networks:
  m3tv:
    external: true
      
#For nfs share  
volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":PATH"
  public:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,rw,soft,nfsvers=4"
      device: ":PATH"