version: "2"
services:

    jellyfin:
      image: lscr.io/linuxserver/jellyfin:latest
      container_name: jellyfin
      environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=jellyfin.example.com
      volumes:
      - /media-server/conf/jellyfin:/config
      - /media-server/media:/media
      - /media-server/media/Airing:/Airing
      - /media-server/media/FinishedAiring:/FinishedAiring
      - /media-server/media/TV Shows:/TV Shows
      - /media-server/media/movies:/movies
      - /media-server/guest/movies:/guest movies      
      - /media-server/guest/Anime:/guest Anime
      - /media-server/guest/shows:/guest shows


      ports:
      - 8096:8096
      restart: unless-stopped


    jackett:
      image: lscr.io/linuxserver/jackett:latest
      container_name: jackett
      environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      volumes:
      - /media-server/conf/jackett:/config
      - /media-server/media:/media
      - /media-server/media/Airing:/Airing
      - /media-server/media/FinishedAiring:/FinishedAiring
      - /media-server/media/TV Shows:/TV Shows
      - /media-server/media/movies:/movies
      - /media-server/guest/movies:/guest movies      
      - /media-server/guest/Anime:/guest Anime
      - /media-server/guest/shows:/guest shows
      ports:
      - 9117:9117
      restart: unless-stopped
    
    transmission:
      image: lscr.io/linuxserver/transmission:latest
      container_name: transmission
      environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      volumes:
      - /media-server/conf/transmission:/config
      - /media-server/media:/media
      - /media-server/media/Airing:/Airing
      - /media-server/media/FinishedAiring:/FinishedAiring
      - /media-server/media/TV Shows:/TV Shows
      - /media-server/media/movies:/movies
      - /media-server/guest/movies:/guest movies      
      - /media-server/guest/Anime:/guest Anime
      - /media-server/guest/shows:/guest shows
      ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      restart: unless-stopped

    radarr:
      image: linuxserver/radarr
      container_name: radarr
      environment:
      - PUID=0
      - PGID=0
      - TZ=America/Denver
      volumes:
      - /media-server/conf/radarr:/config
      - /media-server/media:/media
      - /media-server/media/Airing:/Airing
      - /media-server/media/FinishedAiring:/FinishedAiring
      - /media-server/media/TV Shows:/TV Shows
      - /media-server/media/movies:/movies
      - /media-server/guest/movies:/guest movies      
      - /media-server/guest/Anime:/guest Anime
      - /media-server/guest/shows:/guest shows
      ports:
      - 7878:7878
      restart: unless-stopped

    bazarr:
      image: lscr.io/linuxserver/bazarr:latest
      container_name: bazarr
      environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      volumes:
      - /media-server/conf/bazarr:/config
      - /media-server/media:/media
      - /media-server/media/Airing:/Airing
      - /media-server/media/FinishedAiring:/FinishedAiring
      - /media-server/media/TV Shows:/TV Shows
      - /media-server/media/movies:/movies
      - /media-server/guest/movies:/guest movies      
      - /media-server/guest/Anime:/guest Anime
      - /media-server/guest/shows:/guest shows
      ports:
      - 6767:6767
      restart: unless-stopped
    
    sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      environment:
      - PUID=0
      - PGID=0
      - TZ=America/Denver
      - UMASK_SET=022
      volumes:
      - /media-server/conf/sonarr:/config
      - /media-server/media:/media
      - /media-server/media/Airing:/Airing
      - /media-server/media/FinishedAiring:/FinishedAiring
      - /media-server/media/TV Shows:/TV Shows
      - /media-server/media/movies:/movies
      - /media-server/guest/movies:/guest movies      
      - /media-server/guest/Anime:/guest Anime
      - /media-server/guest/shows:/guest shows
      ports:
      - 8989:8989
      restart: unless-stopped

    requestrr:
      image: lscr.io/linuxserver/requestrr:latest
      container_name: requestrr
      environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      volumes:
      - /media-server/conf/requestrr:/config
      ports:
      - 4545:4545
      restart: unless-stopped

 ----------------------------------------------------------
    
    jellyseerr:
      image: fallenbagel/jellyseerr:latest
      container_name: jellyseerr
      environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tashkent
      ports:
      - 5055:5055
      volumes:
      - /homelab/conf/jellyseerr:/app/config
      - /homelab/media:/media
      - /homelab/media/Airing:/Airing
      - /homelab/media/Finished Airing:/FinishedAiring
      - /homelab/media/TV Shows:/TV Shows
      - /homelab/media/movies:/movies
      restart: unless-stopped

